// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5u9V6io4bN2ihdhXoiox8YFm8Ddcz87o',
    appId: '1:543186587052:web:7ecc5a7a34bca9fad87e09',
    messagingSenderId: '543186587052',
    projectId: 'capoeirafiu-ea8ljo',
    authDomain: 'capoeirafiu-ea8ljo.firebaseapp.com',
    storageBucket: 'capoeirafiu-ea8ljo.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmBdLTQYFqM6Wds-Gegi_jb4ACF762ZBY',
    appId: '1:543186587052:android:3303ab9969fa965ed87e09',
    messagingSenderId: '543186587052',
    projectId: 'capoeirafiu-ea8ljo',
    storageBucket: 'capoeirafiu-ea8ljo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcdJzaOQCAlkCwIn5JDJQakYpxxtTkwiE',
    appId: '1:543186587052:ios:48fe3659fb355840d87e09',
    messagingSenderId: '543186587052',
    projectId: 'capoeirafiu-ea8ljo',
    storageBucket: 'capoeirafiu-ea8ljo.firebasestorage.app',
    iosBundleId: 'com.jumperstudio.gingaApp2026',
  );
}
